### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by Bustami** [JoGall/soccermatics#13]
Hi!
First i tried with `devtools::install_github("jogall/soccermatics")` but the installation not finished ever (i don't know why), 
so then i tried with `install.packages("https://github.com/JoGall/soccermatics/blob/master/soccermatics_0.8.4.tar.gz", repo=NULL, type="source")` but get ERROR "in getOctD(x, offset, len) : invalid octal digit"

Finally i download the .tar compressed folder (version 0.9.0 and 0.8.4) and the installation works but it's not complete. For example function "soccerShotmap" is not include there.

**Comment by JoGall** [comment]
Hey sorry for the late response. Can you try installing with devtools again? And if it still doesn't work can you give me the full error message? Or if installation just hangs without error, your OS and R version.

It's working fine for me at the moment on Ubuntu 16.04 and Windows 10 so no idea what the problem is.

**Comment by Bustami** [comment]
hi mate! sorry for my delayed reply. 
Now  the installation is working, with devtools. i don´t know if you changed something, but i can say that it was more fast than before.
Thanks!

**Comment by JoGall** [comment]
Glad it's working for you now! 👍
